version: '3'

services:

  db:
    image: postgres
    container_name: db
    environment:
      - POSTGRES_DB=postgres # a tu czasami nie mam danych do bazy? co w takim razie jest w dev.env ???
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432
    volumes:
      - ./scripts:/docker-entrypoint-initdb.d

  redis:
    image: redis
    container_name: redis

  rabbitmq:
    image: rabbitmq
    container_name: rabbitmq
    #ports:
    #  - 5672:5672
    #  - 15672:15672

  server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: server
    command: python manage.py runserver 0.0.0.0:8001
    volumes:
      - .:/code
    ports:
      - 8002:8001 # na zewnątrz dokerów apka będzie dostępna na porcie 8002. wewnątrz, pomiędzy serwisami na 8001
    env_file:
      - etc/dev.env
    depends_on:
      - db